apiVersion: v1
kind: Pod
metadata:
  name: todonode
  namespace: todoapp
  labels:
    app: todonode

spec:
  containers:
  - name: todonode
    image: ratnadeepsali/todo:latest
    resources: 
        requests:
            cpu: "50m"
            memory: "90Mi" 
    ports:
      - name: http
        containerPort: 80
        protocol: TCP

---


apiVersion: v1
kind: Service
metadata:
  name: todonodeport
  namespace: todoapp

spec:
  type: NodePort
  selector:
    app: todonode
  ports:
  - port: 80
    targetPort: 80
    name: todonodeport
    protocol: TCP