apiVersion: v1
kind: Pod
metadata:
  name: todolb
  namespace: todoapp
  labels:
    app: todolb

spec:
  containers:
  - name: todolb
    image: swapnil0078/todoapp:latest
    resources: 
        requests:
            cpu: "50m"
            memory: "90Mi" 
    ports:
      - name: http
        containerPort: 80
        protocol: TCP

---


apiVersion: v1
kind: Service
metadata:
  name: todolb
  namespace: todoapp

spec:
  type: LoadBalancer
  selector:
    app: todolb
  ports:
  - port: 80
    targetPort: 80
    name: todolb
    protocol: TCP