apiVersion: apps/v1
kind:  ReplicaSet
metadata: 
       name: studappreplica3
       labels:
            app: studappreplica3
spec: 
    replicas: 4  #how many replica's you want to create on the basis of template
    template:
      metadata:  #like a tag
         labels: 
            app: studappreplica3
      spec:
        containers:
            - name: mypod-cont1
              image: ratnadeepsali/student:latest
              resources: 
                  requests:
                    cpu: "50m"
                    memory: "90Mi"        
              ports:  
                - name: http
                  containerPort: 80
                  protocol: TCP
    selector: 
          matchExpressions: 
            - {key: app, operator: NotIn, values: [studappreplica, studappreplica2]}